string group_name
trajectory_msgs/JointTrajectory joint_trajectory

#goal definition
duration time_offset
string target_link
---
trajectory_msgs/JointTrajectory actual_trajectory
arm_navigation_msgs/ArmNavigationErrorCodes error_code
---
arm_navigation_msgs/RobotState current_state
arm_navigation_msgs/RobotState paused_trajectory_state
arm_navigation_msgs/CollisionObject paused_collision_map

